Read terraform and terragrunt versions from file
pafcloud/terraform-actions pull request #13
Opened 2021-01-18 15:39 UTC by hluotola-paf

If current working directory has `.terraform-version`,  `.terragrunt-version`  use these files to read terraform , terragrunt versions to use later in setup steps.

This is similar to what `tfenv` and `tgenv` are using.

2021-01-18 17:49 UTC, jpalomaki commented on terraform/version/action.yml
> +description: Like tfenv - check path for .terraform-version file and use vesion specified there. Otherwise return default version.
Typo: `vesion`

2021-01-18 17:50 UTC, jpalomaki commented on terragrunt/version/action.yml
> +description: Like tgenv - check path for .terragrimt-version file and use vesion specified there. Otherwise return default version.
Typo: `vesion`

2021-01-18 17:51 UTC, jpalomaki commented on terragrunt/version/action.yml
> +        echo ::set-output name=checksum::${checksums[$version]}
Does this fail gracefully if no hash is available?

2021-01-18 17:52 UTC, jpalomaki requested changes
See inline

2021-01-19 07:55 UTC, conradt-paf commented on terragrunt/version/action.yml
> +        echo ::set-output name=checksum::${checksums[$version]}
Just a thought, would it be wise/possible to include the checksum in .terragrunt-version and .terraform-version files?
This way maybe we wouldn't need hardcoded versions in the action.yml

2021-01-19 08:27 UTC, hluotola-paf commented on terragrunt/version/action.yml
> +        echo ::set-output name=checksum::${checksums[$version]}
> Just a thought, would it be wise/possible to include the checksum in .terragrunt-version and .terraform-version files?
> This way maybe we wouldn't need hardcoded versions in the action.yml

Only content in file is version:

```
$ cat .terraform-version
0.12.30
```

and tfenv/tgenv also reads them, so cannot add sums.

2021-01-19 10:55 UTC, jpalomaki commented on terraform/version/action.yml
> +        version="0.12.29"
W0uld it make sense to move this into an input, defaulting to said value?

2021-01-19 12:34 UTC, hluotola-paf commented on terraform/version/action.yml
> +        version="0.12.29"
Added inputs for default values.

2021-01-19 14:09 UTC, jpalomaki approved these changes

2021-01-19 14:49 UTC, merged