Infracost test
pafcloud/terraform-actions pull request #61
Opened 2022-11-30 11:47 UTC by kimgri

2022-12-01 11:40 UTC, hluotola-paf requested changes

2022-12-01 11:40 UTC, hluotola-paf commented on infracost/action.yml
> +        terragrunt show -json ${{ runner.temp }}/plan.tfplan > ${{ runner.temp }}/plan.json
Path to saved binary plan cloud be input (it can default to this value).

2022-12-01 11:40 UTC, hluotola-paf commented on infracost/action.yml
> +    value: ${{ steps.this.outputs.exit-code }}
Just remove

2022-12-01 11:40 UTC, hluotola-paf commented on terraform/pr-comment/action.yml
> +          details terraform closed "$4" "$summary_title"
Change codeblock syntax  from `terraform` to something else?

2022-12-01 18:35 UTC, jpalomaki commented on infracost/action.yml
> +  WORKING_DIRECTORY:
Please use `kebab-case` for inputs

2022-12-01 18:37 UTC, jpalomaki commented on infracost/action.yml
> +    default: "\n[output truncated, see workflow logs for complete output]"
Not used?

2022-12-01 18:39 UTC, jpalomaki commented on infracost/action.yml
> +        WORKING_DIRECTORY: ${{ inputs.working-directory }}
Shouldn't this just be set on the run step using `working-directory`? Then you could just say e.g.
```
terragrunt show -json plan.tfplan > plan.json
```

2022-12-01 18:40 UTC, jpalomaki commented on infracost/action.yml
> +        infracost configure set currency EUR
Prefer environment variables for config: https://www.infracost.io/docs/features/environment_variables/

2022-12-01 18:42 UTC, jpalomaki commented on infracost/action.yml
> +    value: ${{ steps.this.outputs.summary }}
Whats the difference between output and summary?

2022-12-01 18:43 UTC, jpalomaki commented on infracost/action.yml
> +  Runs infracost to get a cost estimate.
No need to use `>` here since its just one line. Just do
```
description: Runs infracost to get a cost estimate
```

2022-12-01 18:47 UTC, jpalomaki commented
IMO the action should be called `run-infracost` (so it rhymes with https://github.com/pafcloud/terraform-actions/tree/master/run-terragrunt)

2022-12-02 06:40 UTC, kimgri commented on infracost/action.yml
> +  WORKING_DIRECTORY:
kebabcase caused syntax errors, (initially it was $working-directory) in other actions WORKING_DIRECTORY was also used.

2022-12-02 07:06 UTC, jpalomaki commented on infracost/action.yml
> +  WORKING_DIRECTORY:
Kebab case will just fine (and is a convention), see e.g. https://github.com/pafcloud/terraform-actions/blob/master/run-terragrunt/action.yml#L12

2022-12-02 07:53 UTC, kimgri commented on infracost/action.yml
> +    value: ${{ steps.this.outputs.summary }}
Output is the raw output, meaning all of the infracost data.
Summary is just: "Amount: Current -> New : Difference: Current - New "

2022-12-02 11:33 UTC, jpalomaki commented on run-infracost/action.yml
> +name: infracost
```suggestion
name: run-infracost
```

2022-12-08 09:33 UTC, jpalomaki commented on run-infracost/action.yml
> +    default: ${{ runner.temp }}
Remove default value (I guess `terragrunt.hcl` is never in there)?

2022-12-27 12:02 UTC, jpalomaki commented on run-infracost/action.yml
> +  infracost-api-point:
Should this say _endpoint_, rather than _point_?

2022-12-27 12:03 UTC, jpalomaki commented on run-infracost/action.yml
> +        infracost diff --path $tmp_dir/plan.json --format=json --usage-file $RUNNER_TEMP/result.yml >> $tmp_dir/infracost.json
`rersult.yml` sounds strange for usage file name

2022-12-29 07:04 UTC, merged