Hide comment for issue #69
pafcloud/terraform-actions pull request #68
Opened 2023-12-01 11:03 UTC by oveost

This works to minimize previous comment from a plan comment, example below of a run.

![image](https://github.com/pafcloud/terraform-actions/assets/33539730/aed1226d-24e8-492a-9b4c-5ae900a74969)

2024-03-14 07:25 UTC, conradt-paf approved these changes

2024-03-14 08:02 UTC, conradt-paf requested changes

2024-03-14 08:02 UTC, conradt-paf commented on terraform/pr-comment/action.yml
> +      uses: marocchino/sticky-pull-request-comment@v2
We could use commit hash of the release

2024-03-14 08:43 UTC, oveost commented on terraform/pr-comment/action.yml
> +      uses: marocchino/sticky-pull-request-comment@v2
Added. :)

2024-03-20 07:38 UTC, conradt-paf approved these changes

2024-03-20 07:39 UTC, merged